### ISSUE TITLE
Add cabal-file-th package to www.stackage.org

### ISSUE THREAD

**Issue by dysinger** [nkpart/cabal-file-th#4]
http://www.stackage.org/

You get nightly builds out of the deal & notifications if your project ever stops building with the rest of the packages.

We really like your package. It's super useful.  Thanks!

**Comment by nkpart** [comment]
No problem! I've started the process to get it into the package set.

**Comment by dysinger** [comment]
Need any help/examples? (no pressure.)  Are there any issues so far?

**Comment by nkpart** [comment]
It was merged in: https://github.com/fpco/stackage/pull/493

I imagine things are pretty busy in stackage land with the 7.10 release, but I don't see any reason why it won't be in the package set soon. The dependencies of cabal-file-th are pretty light/loose.

**Comment by dysinger** [comment]
ok awesome!

**Comment by dysinger** [comment]
thanks!
