### ISSUE TITLE
Add cabal-file-th to stackage.org?

### ISSUE THREAD

**Issue by dysinger** [nkpart/cabal-file-th#5]
I like this package.  I use it everywhere I create a CLI tool.  I use it to show the cabal version in the optparse-applicative help display.

Could we take a few minutes & add it to stackage.org? the instructions are on the site. It's super easy.

The benefit for you would be nightly builds with all the other (almost 1000) packages being built nightly (plus inclusion in LTS releases).

**Comment by dysinger** [comment]
dogh.  This is already in stackage.  I am a dork.

**Comment by dysinger** [comment]
I've been asking lots of people about their package & forgot we just did this... sorry for the noise. :)

**Comment by nkpart** [comment]
I thought this seemed familiar! :)
