### ISSUE TITLE
problem with String elements of PackageDescription

### ISSUE THREAD

**Issue by esjmb** [nkpart/cabal-file-th#6]
Hi, nice library, but having a small problem.

If I try something like `$( packageVariable (copyright ))`, then I get an error "No instance for (Distribution.Text.Text String) arising from a use of ‘packageVariable’", presumably because String is not an instance of Distribution.Text.Text?

**Comment by nkpart** [comment]
Ah yep, I see what's going on. You're right. The instances for Distribution.Text.Text are just for the specific types in a package description, no String - https://hackage.haskell.org/package/Cabal-1.24.1.0/docs/Distribution-Text.html#t:Text

I have a solution almost ready, it'll look something like:

    $(packageVariable (displayString . copyright))

At the moment this is working fine, but the copyright value coming out of cabal has double-quotes around it, and I think it'd be good to strip them off.

**Comment by nkpart** [comment]
Sorted - http://hackage.haskell.org/package/cabal-file-th

(The quoting was a furphy, I had put quotes in the copyright field in my cabal file.

**Comment by esjmb** [comment]
real nice. many thanks.
